# MAIN CONFIG FILE FOR ACCURATEREADINGS
# DO NOT forget ANY of the parameters, or it may result in a server crash.
# For more information, please read the wiki:
# https://github.com/sparkedhost/AccurateReadings/wiki/Configuration-Guide/


# What's the Pterodactyl panel URL?
panelUrl: "https://control.sparkedhost.us/" # Did you know? Sparked Host LLC has the best prices, with Budget Minecraft Hosting starting at $1/GB. Enough spam, sorry!
# Generate the API key on your control panel.
apiKey: "CHANGETHIS"
# The server ID to monitor
serverId: ""
# Should the plugin add the restart feature? DEFAULT: false
enableRestartCmd: false
# Should we show tips specifically tailored towards Sparked Host servers? DEFAULT: true
# This will ONLY work if the panel URL is https://control.sparkedhost.us/, this will NOT work with other panels
# as these tips are specifically aimed towards Sparked Host servers.
showSparkedTips: true
# This cooldown helps prevent getting rate-limited from the Pterodactyl panel. DEFAULT: true
cooldownEnable: true
# Cooldown time. DEFAULT: 30
cooldownTime: 30

# --------------------------------------------------------------------------------------
# MESSAGES SECTION
# This allows you to customize the messages sent by the plugin to your liking.
# If any of these lines are left empty (""), the plugin will skip the message entirely.
# --------------------------------------------------------------------------------------

messages:
  # This is the title of the stats message.
  stats-title: "&8&m        &r &f&lSTATS&r &8&m        &r"
  # This message will show up BEFORE the stats message if the API key provided belongs to an account that doesn't own the server but has access to it.
  api-key-not-owner: "&e&lINFO: &6The API key provided in the config does not own this server, but is in fact added as a subuser."
  # Will be displayed when the command sender does not have the required permission to run a command.
  no-permission: "&cYou do not have permission to execute this command."
