# MAIN CONFIG FILE FOR ACCURATEREADINGS
# Last updated on AccurateReadings v1.2.0
# DO NOT forget ANY of the parameters, or it may result in a server crash.
# For more information, please read the wiki:
# https://github.com/sparkedhost/AccurateReadings/wiki/Configuration-Guide/


pterodactyl:
  # What's the Pterodactyl panel URL?
  # Note: include the protocol in the URL. Do not add the trailing slash! Example: https://control.sparkedhost.us
  panel-url: "https://control.sparkedhost.us"
  # Generate the API key on your control panel.
  api-key: "CHANGETHIS"
  # The server ID to monitor
  server-id: ""
  # Should the plugin use a websocket for resource usage polling?
  # IMPORTANT NOTE: This is disabled by default as Pterodactyl (more specifically Wings) needs to be configured to allow
  # requests from any origin. Read more here: https://github.com/mattmalec/Pterodactyl4J/issues/24
  use-websocket: false
  # Frequency (in seconds) at which the plugin should make a request to the panel to poll resource usage statistics.
  # This is then converted to in-game ticks.
  # DEFAULT: 2
  update-frequency: 2

restart:
  # Should the plugin add the restart feature? It is experimental and may not always work. DEFAULT: false
  enabled: false
  # Should the plugin also broadcast a message to the entire server if successful? DEFAULT: false
  # NOTE: This has no effect if "enabled" is set false. You can customize the broadcast message below.
  announce-restarts: false

# Customization options for the /perf command or any of its aliases
perf-customization:
  # Command to run right after sending the stats, without the slash. DEFAULT: spigot:tps
  # The player or console that sends the /perf command will also execute this one, so make sure they're able to run it.
  # Leave blank for no command.
  post-command: "spigot:tps"

cooldown:
  # Pretty self-explanatory. This now comes disabled by default as the plugin no longer makes a request every single
  # time the command is run.
  enabled: false
  # Cooldown time in seconds. DEFAULT: 30
  time: 30

# --------------------------------------------------------------------------------------
# MESSAGES SECTION
# This allows you to customize the messages sent by the plugin to your liking.
# If any of these lines are left empty (""), the plugin will skip the message entirely.
# --------------------------------------------------------------------------------------

messages:
  # /perf message body
  # Valid placeholders:
  # - {CURRENTCPU} -> Prints current CPU usage, no % sign
  # - {MAXCPU} -> Prints CPU limit, no % sign
  # - {CURRENTRAM} -> Prints current memory usage, incl. units (MB or GB)
  # - {MAXRAM} -> Prints memory limit, incl. units (MB or GB)
  # - {CURRENTDISK} -> Prints current disk usage, incl. units (MB or GB)
  # - {MAXDISK} -> Prints disk limit, incl. units (MB or GB)
  # - {PLAYERCOUNT} -> Prints current amount of players (does NOT include vanished players)
  # - {MAXPLAYERS} -> Prints total player slots available
  # - {SERVERID} -> Prints server ID being monitored
  # - Any PlaceholderAPI placeholders if the plugin is present
  # If empty, the plugin will use the default value. It will also log a warning in console to let you know.
  stats-message: |
    &8&m        &r &f&lSTATS&r &8&m        &r
    &r &r
    &6&l- CPU: &e{CURRENTCPU}% &7(limit: {MAXCPU}%)
    &6&l- RAM: &e{CURRENTRAM} &7(limit: {MAXRAM})
    &6&l- Disk: &e{CURRENTDISK} &7(limit: {MAXDISK})
    &6&l- Players: &e{PLAYERCOUNT}&7/&f{MAXPLAYERS}
    &r &r

  # Will be displayed when the command sender does not have the required permission to run a command.
  no-permission: "&cYou do not have permission to execute this command."
  # The plugin will broadcast this message to the entire server whenever the restart command is used.
  # This only works with the restart feature of this plugin, and will only display this message if announceRestart is set to true.
  restart-broadcast: "&e&lTHE SERVER IS RESTARTING!"

# DO NOT change this, it's used internally within the plugin to determine the config version.
version: 1
