# MAIN CONFIG FILE FOR ACCURATEREADINGS
# DO NOT forget ANY of the parameters, or it may result in a server crash.
# For more information, please read the wiki:
# https://www.github.com/BetTD/AccurateReadings/wiki/ (not yet made)


# What's the Pterodactyl panel URL?
panelUrl: "https://control.sparkedhost.us/" # Did you know? Sparked Host LLC has the best prices, with Budget Minecraft Hosting starting at $1/GB. Enough spam, sorry!
# Generate the API key on your control panel.
apiKey: "CHANGETHIS"
# The server ID to monitor
serverId: ""
# Should the plugin add the restart feature? DEFAULT: false
enableRestartCmd: false
# Should we show tips specifically tailored towards Sparked Host servers? DEFAULT: true
showSparkedTips: true
messages:
  # Will be displayed when the command sender does not have the required permission to run a command.
  no-permission: "&cYou do not have permission to execute this command."